<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>netcoreapp3.0;netcoreapp3.1;net45;net451;net452;net46;net461;net462;net47;net471;net472;net48;net481;net5.0-windows;net6.0-windows;net7.0-windows;net8.0-windows</TargetFrameworks>
	  <LangVersion>10.0</LangVersion>
	  <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controls\PropertyGrid\Editors\IntegerPropertyEditor.cs" />
    <Compile Remove="Controls\PropertyGrid\Editors\StringPropertyEditor.cs" />
    <Compile Remove="Data\Enum\TipPlacement.cs" />
    <Compile Remove="Interactivity\Commands\ScreenshotCommand.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\dropper.cur" />
    <None Remove="Resources\Effects\BrightnessEffect.ps" />
    <None Remove="Resources\Effects\ColorComplementEffect.ps" />
    <None Remove="Resources\Effects\ColorMatrixEffect.ps" />
    <None Remove="Resources\Effects\ContrastEffect.ps" />
    <None Remove="Resources\Effects\GrayScaleEffect.ps" />
    <None Remove="Resources\Images\GlowWindow\bottom.png" />
    <None Remove="Resources\Images\GlowWindow\bottomleft.png" />
    <None Remove="Resources\Images\GlowWindow\bottomright.png" />
    <None Remove="Resources\Images\GlowWindow\cornerbottomleft.png" />
    <None Remove="Resources\Images\GlowWindow\cornerbottomright.png" />
    <None Remove="Resources\Images\GlowWindow\cornertopleft.png" />
    <None Remove="Resources\Images\GlowWindow\cornertopright.png" />
    <None Remove="Resources\Images\GlowWindow\left.png" />
    <None Remove="Resources\Images\GlowWindow\leftbottom.png" />
    <None Remove="Resources\Images\GlowWindow\lefttop.png" />
    <None Remove="Resources\Images\GlowWindow\right.png" />
    <None Remove="Resources\Images\GlowWindow\rightbottom.png" />
    <None Remove="Resources\Images\GlowWindow\righttop.png" />
    <None Remove="Resources\Images\GlowWindow\top.png" />
    <None Remove="Resources\Images\GlowWindow\topleft.png" />
    <None Remove="Resources\Images\GlowWindow\topright.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\dropper.cur" />
    <Resource Include="Resources\Effects\BrightnessEffect.ps" />
    <Resource Include="Resources\Effects\ColorComplementEffect.ps" />
    <Resource Include="Resources\Effects\ColorMatrixEffect.ps" />
    <Resource Include="Resources\Effects\ContrastEffect.ps" />
    <Resource Include="Resources\Effects\GrayScaleEffect.ps" />
    <Resource Include="Resources\Images\GlowWindow\bottom.png" />
    <Resource Include="Resources\Images\GlowWindow\bottomleft.png" />
    <Resource Include="Resources\Images\GlowWindow\bottomright.png" />
    <Resource Include="Resources\Images\GlowWindow\cornerbottomleft.png" />
    <Resource Include="Resources\Images\GlowWindow\cornerbottomright.png" />
    <Resource Include="Resources\Images\GlowWindow\cornertopleft.png" />
    <Resource Include="Resources\Images\GlowWindow\cornertopright.png" />
    <Resource Include="Resources\Images\GlowWindow\left.png" />
    <Resource Include="Resources\Images\GlowWindow\leftbottom.png" />
    <Resource Include="Resources\Images\GlowWindow\lefttop.png" />
    <Resource Include="Resources\Images\GlowWindow\right.png" />
    <Resource Include="Resources\Images\GlowWindow\rightbottom.png" />
    <Resource Include="Resources\Images\GlowWindow\righttop.png" />
    <Resource Include="Resources\Images\GlowWindow\top.png" />
    <Resource Include="Resources\Images\GlowWindow\topleft.png" />
    <Resource Include="Resources\Images\GlowWindow\topright.png" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Langs\LangProvider.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LangProvider.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Langs\LangProvider.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>LangProvider.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
